# Your workflow name.
name: Deploy to render.

# Run workflow on every push to main branch.
on:
  workflow_dispatch: 
  push:
    branches: [main]
 
# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2


### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Release a Docker container to Render. # Your custom step name
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          # service-id: ${{ secrets.RENDER_SERVICE }}
          service-id: ${{ secrets.RENDER_USERNAME }}
          api-key: ${{ secrets.MY_RENDER_PASSWORD }}
          #api-key: ${{ secrets.MY_RENDER_API_KEY }}
          # Below you must provide variables for your Render app.
